---
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Installing mysql python library
    apt:
      name:
        - python3-mysqldb
      state: present

  - name: Installing mysql
    apt:
      name:
        - mysql-server
      state: present

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Setuping user
    mysql_user:
      name: wordpress
      password: "wordpress"
      host: '%'  
      login_user: wordpress  
      login_password: "wordpress"  
      check_implicit_admin: yes  
      priv: "*.*:ALL,GRANT" 
