---
  - name: Creating a new database  
    mysql_db: 
      name: wordpress 
      state: present 
      login_user: wordpress 
      login_password: "wordpress"

  - name: Setuping mysql master config
    template:
      src: templates/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

